// SLIGHT tweaks needed in order to work with the
// autogenerated part (which is still in development)

// variable which stores a boolean variable
// representing if the form is shown
let shown = false;

// diplaying the form function
function display_form() {
    shown = true;
    if (window.innerWidth >= 921) {
        document.getElementById("upload_form").style.display = "block";
        document.getElementById("books").style.marginTop = "30px";
    }
    else if (window.innerWidth > 650) {
        document.getElementById("upload_form").style.display = "block";
        document.getElementById("books").style.marginTop = "67px";
    }
    else
    {
        document.getElementById("upload_form").style.display = "block";
        document.getElementById("books").style.display = "none";
    }
}

// hiding the form function
function hide_form() {
    shown = false;
    if (window.innerWidth >= 921)
    {
        document.getElementById("upload_form").style.display = "none";
        document.getElementById("books").style.marginTop = "";
    }
    else if (window.innerWidth > 650)
    {
        document.getElementById("upload_form").style.display = "none";
        document.getElementById("books").style.marginTop = "";
    }
    else
    {
        // window.location.replace("home.html");
        document.getElementById("upload_form").style.display = "none";
        document.getElementById("books").style.display = "flex";
        document.getElementById("books").style.marginTop = "";
    }
}

// listening for resizing, to scale the form
// accordingly. Not throughly tested
window.addEventListener('resize', function() {
    if (window.innerWidth >= 921 && shown == true) {
        document.getElementById("books").style.marginTop = "30px";
    }
    if (window.innerWidth <= 921 && shown == true) {
        document.getElementById("books").style.marginTop = "67px";
    }
    if (window.innerWidth <= 921 && shown == false) {
        document.getElementById("books").style.marginTop = "";
    }

    if (window.innerWidth >= 650 && shown == true) {
        document.getElementById("upload_form").style.display = "block";
        document.getElementById("books").style.display = "flex";
    }
    if (window.innerWidth >= 650 && shown == false) {
        document.getElementById("upload_form").style.display = "none";
        document.getElementById("books").style.marginTop = "";
    }

    if (window.innerWidth < 650 && shown == false) {
        document.getElementById("books").style.display = "flex";
        document.getElementById("books").style.marginTop = "";
    }
    if (window.innerWidth < 650 && shown == true) {
        document.getElementById("books").style.display = "none";
    }
});